#Since assigning our bot's token and secret here would be very dangerous,
#please just assign it locally after you cloned it. Thank you.
line.bot:
  channel-token: #Our channel token
  channel-secret: #Our secret token
  handler.path: /callback
